format = """
$git_branch\
$git_status\
$directory\
$character
"""

right_format = """
$cmd_duration\
"""

add_newline = false

[directory]
format = "[ [$read_only]($read_only_style)$path ]($style)"
style = "bg:black"
read_only = "󰌾 "
read_only_style = "fg:red bg:black"
truncation_symbol = "<"
truncation_length = 3

[character]
format = " "

[git_branch]
format = "[ $branch(:$remote_branch) ]($style)"
style = "fg:black bg:blue"

[git_status]
format = "[ $all_status$ahead_behind ]($style)\n"
style = "fg:black bg:cyan"
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[cmd_duration]
min_time = 500
format = "[ $duration ]($style)"
style = "fg:black bg:yellow"
